let mock = [{"id":1,"car_make":"Nissan","car_model":"Altima","car_model_year":2000},
{"id":2,"car_make":"Ford","car_model":"Tempo","car_model_year":1994},
{"id":3,"car_make":"Kia","car_model":"Sportage","car_model_year":1995},
{"id":4,"car_make":"Mazda","car_model":"626","car_model_year":1996},
{"id":5,"car_make":"Lincoln","car_model":"Town Car","car_model_year":1994},
{"id":6,"car_make":"Hyundai","car_model":"Sonata","car_model_year":2002},
{"id":7,"car_make":"Ford","car_model":"Econoline E250","car_model_year":1995},
{"id":8,"car_make":"Volvo","car_model":"C70","car_model_year":2000},
{"id":9,"car_make":"Lexus","car_model":"LX","car_model_year":2010},
{"id":10,"car_make":"Chevrolet","car_model":"Suburban","car_model_year":2009},
{"id":11,"car_make":"Ford","car_model":"Mustang","car_model_year":2000},
{"id":12,"car_make":"Chevrolet","car_model":"Express 1500","car_model_year":1999},
{"id":13,"car_make":"Porsche","car_model":"Boxster","car_model_year":2008},
{"id":14,"car_make":"Subaru","car_model":"Legacy","car_model_year":2000},
{"id":15,"car_make":"Maybach","car_model":"57","car_model_year":2007},
{"id":16,"car_make":"Nissan","car_model":"Altima","car_model_year":1995},
{"id":17,"car_make":"Acura","car_model":"Legend","car_model_year":1995},
{"id":18,"car_make":"Volvo","car_model":"C70","car_model_year":2000},
{"id":19,"car_make":"Audi","car_model":"A7","car_model_year":2012},
{"id":20,"car_make":"Subaru","car_model":"Legacy","car_model_year":2006},
{"id":21,"car_make":"Mercedes-Benz","car_model":"E-Class","car_model_year":1995},
{"id":22,"car_make":"Mercedes-Benz","car_model":"G-Class","car_model_year":2003},
{"id":23,"car_make":"Pontiac","car_model":"Grand Prix","car_model_year":1994},
{"id":24,"car_make":"Lincoln","car_model":"Navigator L","car_model_year":2007},
{"id":25,"car_make":"Land Rover","car_model":"Defender","car_model_year":1993},
{"id":26,"car_make":"BMW","car_model":"7 Series","car_model_year":1993},
{"id":27,"car_make":"Ford","car_model":"LTD Crown Victoria","car_model_year":1987},
{"id":28,"car_make":"Saab","car_model":"900","car_model_year":1993},
{"id":29,"car_make":"Audi","car_model":"A8","car_model_year":2012},
{"id":30,"car_make":"Pontiac","car_model":"LeMans","car_model_year":1989}]

export default mock;